### ISSUE TITLE
IllegalAccessError: tried to access method net.imglib2.util.StopWatch.<init>

### ISSUE THREAD

**Issue by haesleinhuepf** [maarzt/imglib2-labkit#30]
Hi @maarzt ,

I just tried Labkit for the first time. It came via update site to my Fiji on Windows 10 64 bit with Java 1.8. I opened an image and clicked the menu Plugins > Segmentation > Labkit. An error came up:

Exception in thread "PainterThread" java.lang.IllegalAccessError: tried to access method net.imglib2.util.StopWatch.<init>()V from class net.imglib2.cache.iotiming.IoStatistics
	at net.imglib2.cache.iotiming.IoStatistics.<init>(IoStatistics.java:21)
	at net.imglib2.cache.iotiming.CacheIoTiming.getIoStatistics(CacheIoTiming.java:30)
	at net.imglib2.cache.iotiming.CacheIoTiming.getIoStatistics(CacheIoTiming.java:17)
	at net.imglib2.cache.iotiming.CacheIoTiming.getIoTimeBudget(CacheIoTiming.java:40)
	at bdv.viewer.render.MultiResolutionRenderer.createProjector(MultiResolutionRenderer.java:658)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:496)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:485)
	at net.imglib2.ui.PainterThread.run(PainterThread.java:86)

Furthermore, the viewer is empty:
![image](https://user-images.githubusercontent.com/12660498/49655761-d0ece280-fa3b-11e8-9d5a-1e83e4f18024.png)

Is there maybe something wrong with the installation via update site? A dependency might be missing? Any hint would be helpful!

Cheers,
Robert

**Comment by maarzt** [comment]
@haesleinhuepf This bug is fixed already :) There was a problem within imglib2-cache.
